name: Publish Docker image
on:
  push:
    branches:
      - main 
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:      
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: mgkaiser/webtest1
          # generate Docker tags based on the following events/attributes
          flavor: |
            latest=true
          tags: |
            type=sha
            type=raw,enable=true,prefix=Build-,value=${{ github.run_number }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true          
          tags:   ${{ steps.meta.outputs.tags }} 
          labels: ${{ steps.meta.outputs.labels }}  
      - name: Update the helm chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAGS: ${{ steps.meta.outputs.tags }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          git clone https://mkaiserincomm:$GITHUB_TOKEN@github.com/mkaiserincomm/webtest1-helm
          git config --global user.email "mkaiser@incomm.com"
          git config --global user.name "Michael Kaiser"
          cd webtest1-helm
          cat ./charts/webtest1/values.yaml | sed 's/tag: \"latest\"/tag: \"'$GITHUB_TAGS'\"/' > ./charts/webtest1/values2.yaml
          mv ./charts/webtest1/values2.yaml ./charts/webtest1/values.yaml
          git add ./charts/webtest1/values.yaml
          git commit -m "Updated build number"
          git push --set-upstream https://mkaiserincomm:$API_TOKEN@github.com/mkaiserincomm/webtest1-helm

